---
# To run this plabook add tags facts and network
# Facts will retrieve environment variable such is ip, network configurations, OS version, remote user, etc
# Network tag installs Cilium network plugin and checks that the configuration is well set up.
# Exmaple how to run this playbook:
# ansible-playbook -i inventory/kubespray-aws-inventory.py cilium.yml -b -t facts,network

- hosts: k8s-cluster:etcd
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  gather_facts: false
  vars:
  ansible_ssh_pipelining: false
  roles:
    - { role: bootstrap-os, tags: bootstrap-os}

- hosts: k8s-cluster
  any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
  roles:
    - { role: kubespray-defaults}
    - { role: network_plugin, tags: network }

 - hosts: kube-master
   any_errors_fatal: "{{ any_errors_fatal | default(true) }}"
   roles:
     - { role: kubespray-defaults}
     - { role: kubernetes-apps/network_plugin, tags: network }
     - { role: kubernetes-apps/policy_controller, tags: policy-controller }
     - { role: kubernetes-apps/ingress_controller, tags: ingress-controller }
     - { role: kubernetes-apps/external_provisioner, tags: external-provisioner }
